# -*- coding: utf-8 -*-
"""Question one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRFeeNfJDJV9E0wCW8h5jB-Er5CA8k1l

Stage (t): Each month, t = 1, 2, 3, 4, 5, 6

State (s): The number of trained bakers at the start of each month, before any hiring or departures.

Action (x): The number of new trainees hired at the start of each month. x ≥ 0.


d(t) = trained bakers needed each month: 10, 12, 13, 11, 14, 11
q(t) = trained bakers leaving at end of month: 1, 2, 1, 3, 2, 0

State Transition Function:
At the start of month t, you have s trained bakers. You hire x trainees. Those x trainees from the previous month become trained bakers at the start of the next month. Trained bakers lost at end of month t = q(t).
So:

s(t+1) = s(t) + x(t-1) - q(t)

Where x(t-1) are last month's trainees who are now trained.


Contribution Function (Cost):
Each month's payroll cost is:

Trained bakers cost: 2000 × s(t)

Trainee cost: 1200 × x(t)

But each trainee requires 0.5 month of a trained baker's time for supervision, so effective trained baker capacity is reduced: s(t) - 0.5x(t) ≥ d(t)

So the constraint is:

s(t) - 0.5x(t) ≥ d(t) → meaning x(t) ≤ 2(s(t) - d(t))

Monthly cost:

C(s, x, t) = 2000·s(t) + 1200·x(t)

DP Recursion:

f(s, t) = min over x { 2000·s + 1200·x + f(s(t+1), t+1) }

With boundary condition f(s, 6) = 2000·s (no trainees hired in last month since bakery closes).
"""

import numpy as np
import pandas as pd

# ── Problem Parameters ───────────────────────────────────────────────────────
d = {1: 10, 2: 12, 3: 13, 4: 11, 5: 14, 6: 11}   # trained bakers needed
q = {1: 1,  2: 2,  3: 1,  4: 3,  5: 2,  6: 0}    # trained bakers leaving at end of month
initial_bakers = 12                                 # starting trained bakers
MAX_BAKERS = 30                                     # upper bound on state space

# ── DP Tables ────────────────────────────────────────────────────────────────
# f[t][s] = minimum cost from month t onwards, given s trained bakers at start of month t
# x_opt[t][s] = optimal number of trainees to hire at month t given state s

INF = float('inf')
f     = {t: {} for t in range(1, 8)}   # t=7 is the terminal or the dummy state (post month 6)
x_opt = {t: {} for t in range(1, 7)}

# ── Terminal Condition: after month 6, bakery closes, cost = 0 ───────────────
for s in range(MAX_BAKERS + 1):
    f[7][s] = 0

# ── Backward Induction ───────────────────────────────────────────────────────
for t in range(6, 0, -1):
    for s in range(MAX_BAKERS + 1):

        best_cost = INF
        best_x    = None

        # determine feasible range of x (trainees hired this month)
        # constraint: s - 0.5*x >= d[t]  =>  x <= 2*(s - d[t])
        max_x = int(2 * (s - d[t])) if s >= d[t] else -1

        if max_x < 0:
            # not enough trained bakers even with no trainees — infeasible state
            f[t][s]     = INF
            x_opt[t][s] = None
            continue

        for x in range(0, max_x + 1):
            # next state: trainees hired THIS month become trained NEXT month
            # s(t+1) = s(t) + x(t) - q(t)
            s_next = s + x - q[t]

            if s_next < 0 or s_next > MAX_BAKERS:
                continue

            future_cost = f[t + 1].get(s_next, INF)
            if future_cost == INF:
                continue

            monthly_cost = 2000 * s + 1200 * x
            total_cost   = monthly_cost + future_cost

            if total_cost < best_cost:
                best_cost = total_cost
                best_x    = x

        f[t][s]     = best_cost
        x_opt[t][s] = best_x

# ── Trace Optimal Path from initial state ────────────────────────────────────
print("=" * 60)
print("       BAKERY STAFFING - OPTIMAL DP SOLUTION")
print("=" * 60)

s = initial_bakers
total_cost = 0
results = []

for t in range(1, 7):
    x     = x_opt[t].get(s)
    cost  = 2000 * s + 1200 * x if x is not None else INF
    s_next = s + x - q[t] if x is not None else None

    results.append({
        "Month (t)"               : t,
        "Trained Bakers (s)"      : s,
        "Trainees Hired (x)"      : x,
        "Bakers Needed (d)"       : d[t],
        "Effective Capacity"      : s - 0.5 * x if x is not None else None,
        "Bakers Leaving (q)"      : q[t],
        "Next Month Bakers (s+1)" : s_next,
        "Monthly Cost ($)"        : cost
    })

    total_cost += cost
    s = s_next

df = pd.DataFrame(results)
print(df.to_string(index=False))
print("=" * 60)
print(f"  TOTAL MINIMUM PAYROLL COST: ${total_cost:,.0f}")
print("=" * 60)

